[package]
name = "netlist-db"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["Junzhuo <zhou@junzhuo.site>"]
keywords = ["eda", "spice", "netlist", "database", "parser"]
readme = "README.md"
repository = "https://github.com/zao111222333/netlist-db/"
documentation = "https://docs.rs/netlist-db"
categories = ["development-tools"]
description = "Concurrent/Parallel SPICE (HSPICE) parser, under building."
include = ["/src", "/examples", "README.md"]

[features]
defualt = []

[dependencies]
fast-float2 = "0.2.3"
indexmap = "2.7.1"
log = "0.4.25"
nom = "8"
nom_locate = "5"
regex = "1.11.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
anstyle = "1.0.8"

[dev-dependencies]
console = "0.15"
similar = { version = "2.7", features = ["inline"] }
simple_logger = "5.0.0"

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1.43"