[workspace]
members = ["pybind"]
[workspace.package]
version = "0.2.4"

[workspace.dependencies]
polars = { version = "0.46", features = ["fmt", "dtype-date", "timezones", "lazy"], default-features = false }
polars-arrow = { version = "0.46", default-features = false }
pyo3 = { version = "0.23", features = ["abi3-py310"] }
pyo3-polars = { version = "0.20", features = ["derive", "lazy"] }
tokio = { version = "1.43.0", features = ["full"] }
simple_logger = "5.0.0"
log = "0.4.25"

[package]
name = "netlist-db"
version.workspace = true
edition = "2024"
license = "MIT"
authors = ["Junzhuo <zhou@junzhuo.site>"]
keywords = ["eda", "spice", "netlist", "database", "parser"]
readme = "README.md"
repository = "https://github.com/zao111222333/netlist-db/"
documentation = "https://docs.rs/netlist-db"
categories = ["development-tools"]
description = "Concurrent/Parallel SPICE (HSPICE) parser, under building."
include = ["/src", "/examples", "README.md"]

[features]
defualt = []
py = ['dep:pyo3', 'dep:polars', 'dep:pyo3-polars', 'dep:polars-arrow']

[dependencies]
fast-float2 = "0.2.3"
indexmap = "2.7.1"
log.workspace = true
nom = "8"
nom_locate = "5"
regex = "1.11.1"
thiserror = "2.0.11"
tokio.workspace = true
anstyle = "1.0.8"
colored = "2.1"
pyo3 = { workspace = true, optional = true }
pyo3-polars = { workspace = true, optional = true }
polars = { workspace = true, optional = true }
polars-arrow = { workspace = true, optional = true }

[dev-dependencies]
console = "0.15"
similar = { version = "2.7", features = ["inline"] }
simple_logger.workspace = true

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1.43"