[workspace]
members = ["pybind", "macros"]
[workspace.package]
version = "0.4.7"
edition = "2024"
license = "MIT"
authors = ["Junzhuo <zhou@junzhuo.site>"]
keywords = ["eda", "spice", "netlist", "database", "parser"]
readme = "README.md"
repository = "https://github.com/zao111222333/netlist-db/"
documentation = "https://docs.rs/netlist-db"
categories = ["development-tools"]
description = "Concurrent/Parallel SPICE (HSPICE) parser, under building."

[workspace.dependencies]
# polars = { version = "0.48", features = ["fmt", "dtype-date", "timezones", "lazy"], default-features = false }
# polars-arrow = { version = "0.48", default-features = false }
# pyo3-polars = { version = "0.21", features = ["derive", "lazy"] }
pyo3 = "0.26"
pyo3-stub-gen = { version = "0.13", default-features = false }
# pyo3-stub-gen = { path = "../../pyo3-stub-gen-main/pyo3-stub-gen", default-features = false }
tokio = { version = "1.47", features = ["fs", "sync", "rt", "rt-multi-thread", "macros", "time"] }
simple_logger = "5.0.0"
log = "0.4.28"
fast-float2 = "0.2.3"
indexmap = "2.11"
nom = "8"
nom_locate = "5"
regex = "1.11"
thiserror = "2"
nu-ansi-term = "0.50"
colored = "3"
itertools = "0.14"
tracing = "0.1.41"
tracing-subscriber = { version="0.3.0", features=["chrono"] }

[package]
name = "netlist-db"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
categories.workspace = true
description.workspace = true
include = ["/src", "/examples", "README.md"]

[features]
defualt = []
py = ['dep:pyo3', 'dep:pyo3-stub-gen']
# py = ['dep:pyo3', 'dep:polars', 'dep:pyo3-polars', 'dep:polars-arrow', 'dep:pyo3-stub-gen']
tracing = ["dep:tracing"]

[dependencies]
netlist-macros = { path = "macros" }
fast-float2.workspace = true
indexmap.workspace = true
log.workspace = true
nom.workspace = true
nom_locate.workspace = true
regex.workspace = true
thiserror.workspace = true
itertools.workspace = true
tokio.workspace = true
nu-ansi-term.workspace = true
colored.workspace = true
pyo3 = { workspace = true, optional = true }
pyo3-stub-gen = { workspace = true, optional = true }
# pyo3-polars = { workspace = true, optional = true }
# polars = { workspace = true, optional = true }
# polars-arrow = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
console = "0.15"
similar = { version = "2.7", features = ["inline"] }
simple_logger.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = "0.1.43"